services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prime_app-web_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      web_db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  web_db:
    image: postgres:15
    container_name: prime_app-web_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prime_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: